### ISSUE TITLE
How to train the importance map?

### ISSUE THREAD

**Issue by lzhzju** [adityassrana/Content-Weighted-Image-Compression#4]
Sorry to bother you...
How can I train the importance map with your code? Thank you in advance!

**Comment by adityassrana** [comment]
Hi @lzhzju, I have posted a [reply](https://github.com/adityassrana/Content-Weighted-Image-Compression/issues/2#issuecomment-819086368) in one of the other issues #2 . Have a look and let me know if it's a bit more clear or post a question in the other issue so that all posts related to it are in one place :)
